/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Garance
 */
public class DMRPatient extends javax.swing.JPanel {

    /**
     * Creates new form DMRPatient
     */
    public DMRPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dmr_panel = new javax.swing.JPanel();
        id_patient_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nom_patient = new javax.swing.JLabel();
        prenom_patient = new javax.swing.JLabel();
        date_naissance = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        adresse = new javax.swing.JLabel();
        num_secu = new javax.swing.JLabel();
        exams = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_exams = new javax.swing.JTable();
        new_exam = new javax.swing.JButton();
        selection_button = new javax.swing.JButton();

        id_patient_panel.setBackground(new java.awt.Color(255, 255, 255));
        id_patient_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient"));

        jLabel8.setText("Nom :");

        jLabel9.setText("Prénom :");

        jLabel10.setText("Date de naissance :");

        jLabel11.setText("Adresse :");

        jLabel12.setText("Email :");

        jLabel13.setText("Tel :");

        jLabel14.setText("N° de sécurité sociale :");

        nom_patient.setText("John");

        prenom_patient.setText("Doe");

        date_naissance.setText("01/01/1900");

        email.setText("john.doe@gmail.com");

        tel.setText("06 99 99 99 99");

        adresse.setText("12 rue de Paris, Grenoble");

        num_secu.setText("JLabel");

        javax.swing.GroupLayout id_patient_panelLayout = new javax.swing.GroupLayout(id_patient_panel);
        id_patient_panel.setLayout(id_patient_panelLayout);
        id_patient_panelLayout.setHorizontalGroup(
            id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_patient_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_naissance))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(adresse))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom_patient))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(num_secu))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenom_patient))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email))
                    .addGroup(id_patient_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        id_patient_panelLayout.setVerticalGroup(
            id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_patient_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nom_patient))
                .addGap(18, 18, 18)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prenom_patient))
                .addGap(18, 18, 18)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(date_naissance))
                .addGap(18, 18, 18)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(email))
                .addGap(18, 18, 18)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tel))
                .addGap(16, 16, 16)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(id_patient_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(num_secu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exams.setBackground(new java.awt.Color(255, 255, 255));
        exams.setBorder(javax.swing.BorderFactory.createTitledBorder("Examens"));

        table_exams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Type", "PH responsable"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_exams.setToolTipText("");
        jScrollPane1.setViewportView(table_exams);

        javax.swing.GroupLayout examsLayout = new javax.swing.GroupLayout(exams);
        exams.setLayout(examsLayout);
        examsLayout.setHorizontalGroup(
            examsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                .addContainerGap())
        );
        examsLayout.setVerticalGroup(
            examsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        new_exam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add (2).png"))); // NOI18N
        new_exam.setText("  Créer un nouvel examen");

        selection_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-view-32.png"))); // NOI18N
        selection_button.setText("  Voir l'examen sélectionné");
        selection_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selection_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dmr_panelLayout = new javax.swing.GroupLayout(dmr_panel);
        dmr_panel.setLayout(dmr_panelLayout);
        dmr_panelLayout.setHorizontalGroup(
            dmr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmr_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(id_patient_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(exams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(dmr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(new_exam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selection_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        dmr_panelLayout.setVerticalGroup(
            dmr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmr_panelLayout.createSequentialGroup()
                .addGroup(dmr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dmr_panelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(dmr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_patient_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dmr_panelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(new_exam)
                        .addGap(26, 26, 26)
                        .addComponent(selection_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dmr_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dmr_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selection_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresse;
    private javax.swing.JLabel date_naissance;
    private javax.swing.JPanel dmr_panel;
    private javax.swing.JLabel email;
    private javax.swing.JPanel exams;
    private javax.swing.JPanel id_patient_panel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton new_exam;
    private javax.swing.JLabel nom_patient;
    private javax.swing.JLabel num_secu;
    private javax.swing.JLabel prenom_patient;
    private javax.swing.JButton selection_button;
    private javax.swing.JTable table_exams;
    private javax.swing.JLabel tel;
    // End of variables declaration//GEN-END:variables
}
